name: bazar_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

dependencies:
  ansicolor: ^2.0.3
  args: ^2.4.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  hive: ^2.2.3
  image: ^4.5.2
  intl: ^0.20.1
  path: ^1.9.1
  postgres: ^3.4.3
  shelf: ^1.4.0
  shelf_multipart: ^2.0.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
